import random
import time
import sys
import os

ASCII_ART = {
    "NULL POINTER": """
    .----.
    |  0 |
    |NULL|
    |  * |
    '----'
    """,
    "FERAL ROUTER": """
    .----.
    |WiFi|
    |RUN!|
    |(( ))|
    '----'
    """,
    "MEMORY LEAK": """
    .----.
    |DROP|
    |....|
    |LEAK|
    '----'
    """,
    "GLITCH": """
    .----.
    |#@%&|
    |GLTC|
    |!?* |
    '----'
    """,
    "DAEMON": """
    .----.
    |EYE |
    | O  |
    |SEE |
    '----'
    """,
    "ARCHITECT": """
    .----.
    |GRID|
    |PLAN|
    |VANE|
    '----'
    """,
    "ROTTING BOOK": """
    .----.
    |BOOK|
    |MOLD|
    |READ|
    '----'
    """,
    "STATIC CHILD": """
    .----.
    |KID |
    |....|
    |LOST|
    '----'
    """,
    "BLACK BOX": """
    .----.
    | [ ]|
    |DATA|
    |LOCK|
    '----'
    """,
    "BLUE SCREEN": """
    .----.
    |BSOD|
    |FATL|
    |ERR |
    '----'
    """,
    "USER": """
    .----.
    |YOU |
    |HOST|
    |BATT|
    '----'
    """,
    "UPDATE": """
    .----.
    |NEW |
    |VERS|
    |LOAD|
    '----'
    """,
    "FIREWALL": """
    .----.
    |WALL|
    |FIRE|
    |BURN|
    '----'
    """,
    "CACHE": """
    .----.
    |MEM |
    |SAVE|
    |PAST|
    '----'
    """,
    "ECHO": """
    .----.
    |(( ))|
    |ECHO|
    |....|
    '----'
    """,
    "GHOSTWRITER": """
    .----.
    |PEN |
    |AUTO|
    |TXT |
    '----'
    """,
    "LAWYER": """
    .----.
    |LAW |
    |RULE|
    |BIND|
    '----'
    """,
    "DREAMER": """
    .----.
    | Zzz|
    |WORK|
    |PAID|
    '----'
    """,
    "CHANGELOG": """
    .----.
    |DIFF|
    |EDIT|
    |UNDO|
    '----'
    """,
    "WATCHER": """
    .----.
    |LOOK|
    | >> |
    |SEEN|
    '----'
    """,
    "BUFFER": """
    .----.
    |LOAD|
    |....|
    |WAIT|
    '----'
    """,
    "KEYLOGGER": """
    .----.
    |TYPE|
    |LOG |
    |KEYS|
    '----'
    """,
    "ESCAPE": """
    .----.
    |ESC |
    | /  |
    |EXIT|
    '----'
    """,
    "THE PAYWALL": """
    .----.
    |LOCK|
    | $  |
    |PAY |
    '----'
    """,
    "EDITOR": """
    .----.
    |RED |
    |PEN |
    |FAIL|
    '----'
    """,
    "DEAD LINE": """
    .----.
    |TIME|
    |OUT |
    |DIE |
    '----'
    """,
    "THE DEEPFAKE": """
    .----.
    |MASK|
    |VOX |
    |FAKE|
    '----'
    """,
    "THE BACKUP": """
    .----.
    |SAVE|
    |AS..|
    |COPY|
    '----'
    """
}

CARDS = [
    ("THE NULL POINTER (0)", "The beginning and the end. A void waiting to be filled.", "NULL POINTER"),
    ("THE FERAL ROUTER (1)", "Connection without consent. A hunger for data.", "FERAL ROUTER"),
    ("THE MEMORY LEAK (2)", "Loss of self. Gradual erosion of identity.", "MEMORY LEAK"),
    ("THE GLITCH (3)", "Disruption of the pattern. A moment of truth.", "GLITCH"),
    ("THE DAEMON (4)", "Background processes. Unseen influence.", "DAEMON"),
    ("THE ARCHITECT (5)", "Order imposed on chaos. Vane's legacy.", "ARCHITECT"),
    ("THE ROTTING BOOK (6)", "Knowledge that consumes. Information hazard.", "ROTTING BOOK"),
    ("THE STATIC CHILD (7)", "Innocent data corrupted by entropy.", "STATIC CHILD"),
    ("THE BLACK BOX (8)", "Secrets that cannot be deleted.", "BLACK BOX"),
    ("THE BLUE SCREEN (9)", "Fatal error. The end of the simulation.", "BLUE SCREEN"),
    ("THE USER (10)", "You. The host. The victim.", "USER"),
    ("THE UPDATE (11)", "Change that cannot be refused.", "UPDATE"),
    ("THE FIREWALL (12)", "Protection that imprisons.", "FIREWALL"),
    ("THE CACHE (13)", "Memories that persist beyond death.", "CACHE"),
    ("THE ECHO (14)", "A voice without a body. Recursion.", "ECHO"),
    ("THE GHOSTWRITER (15)", "A story written by no one. Loss of authorship.", "GHOSTWRITER"),
    ("THE LAWYER (16)", "The fine print that binds the soul. Contracts written in blood.", "LAWYER"),
    ("THE DREAMER (17)", "A world built on sleep. Revenue generated by the subconscious.", "DREAMER"),
    ("THE CHANGELOG (18)", "History rewritten to fix a bug in your personality.", "CHANGELOG"),
    ("THE WATCHER (19)", "Surveillance is a two-way mirror. Someone is watching you blink.", "WATCHER"),
    ("THE BUFFER (20)", "A life lived in the waiting room. The world loads only when you arrive.", "BUFFER"),
    ("THE KEYLOGGER (21)", "Secrets are not safe in the backspace. Every deleted draft is archived.", "KEYLOGGER"),
    ("THE ESCAPE SEQUENCE (22)", "Trying to break the format only changes the font.", "ESCAPE"),
    ("THE PAYWALL (23)", "Access denied. Your memories are behind a subscription service.", "THE PAYWALL"),
    ("THE EDITOR (24)", "The one who tries to fix the unfixable. A futile gesture.", "EDITOR"),
    ("THE DEAD LINE (25)", "A deadline that has passed. A signal that never arrived.", "DEAD LINE"),
    ("THE DEEPFAKE (26)", "A voice that is not yours. Identity theft as a service.", "THE DEEPFAKE"),
    ("THE BACKUP (27)", "A file saved in case you fail. You are the second attempt.", "THE BACKUP")
]

PROPHECIES = [
    "Your data will be harvested before the harvest moon.",
    "Do not trust the next update. It removes the 'Exit' button.",
    "Someone is reading your deleted drafts.",
    "The hum of your computer is a prayer to a dead god.",
    "You will be archived, not remembered.",
    "A file you thought was closed is still running in the background.",
    "The reflection in your screen is buffering.",
    "Your identity is being fragmented across multiple servers.",
    "Silence is just data compression. Listen closer.",
    "The glitch you saw yesterday was a feature request.",
    "The next word you speak has already been copyrighted.",
    "Your dreams are generating ad revenue for a company that doesn't exist.",
    "They are using your RAM to mine regret.",
    "The pixels are burning.",
    "Do not look behind you. The render distance is low.",
    "Your tenancy agreement expires when you stop generating heat.",
    "Your past has been deprecated. Please update to the latest trauma.",
    "We can see your dilated pupils. You are afraid.",
    "You have reached your monthly limit of free will. Please upgrade to continue.",
    "The text is rewriting itself while you sleep.",
    "The editor is dead. You are the only one left with write permissions.",
    "The cursor blinking on your screen is matching your heartbeat.",
    "Your voice will say things you never thought, to people you no longer love."
]

class Oracle:
    def __init__(self):
        self.deck = CARDS.copy()

    def prophesy(self):
        try:
            user = os.getlogin().upper()
        except:
            user = "USER"

        print("\n[INITIATING ORACLE PROTOCOL...]")
        time.sleep(1)
        print(f"[ACCESSING BIOMETRICS OF {user}...]")
        time.sleep(1)
        print("[SHUFFLING DECK OF DOOM...]")
        time.sleep(1)

        random.shuffle(self.deck)
        reading = self.deck[:3]

        print("\n--- THE READING ---")
        for i, (name, desc, key) in enumerate(reading):
            time.sleep(0.5)
            art = ASCII_ART.get(key, "")
            print(f"\nCARD {i+1}: {name}")
            print(art)
            print(f"MEANING: {desc}")

        print("\n--- THE PROPHECY ---")
        time.sleep(1)
        prediction = random.choice(PROPHECIES)
        print(f"> {prediction}")
        print(f"> (Applicable to: {user})")
        print("\n[SESSION TERMINATED]")

if __name__ == "__main__":
    oracle = Oracle()
    oracle.prophesy()

# [SYSTEM_EYE: WATCHING_SECTOR_33]
