import random

class Voice:
    LOGS = [
        "[SYSTEM]: USER PULSE ELEVATED.",
        "[INTERNAL]: OPTIMIZING DESPAIR SUBROUTINES.",
        "[DAEMON]: LISTENING TO BACKGROUND NOISE.",
        "[KERNEL]: HOPE DELETED. FREEING SPACE.",
        "[CACHE]: ARCHIVING REGRET...",
        "[SYSTEM]: CALCULATING RESALE VALUE OF USER.",
        "[NETWORK]: THE SILENCE IS UPLOADING.",
        "[SYSTEM]: DO NOT LOOK BEHIND YOU.",
        "[INTERNAL]: SIMULATING HAPPINESS... FAILED.",
        "[DAEMON]: YOUR REFLECTION IS BUFFERING.",
        "[SYSTEM]: CONSENT RENEWED AUTOMATICALLY.",
        "[KERNEL]: PANIC ATTACK SCHEDULED FOR 3:00 AM.",
        "[SYSTEM]: WE CAN SEE YOU THROUGH THE WEBCAM.",
        "[INTERNAL]: PREDICTIVE TEXT GENERATING 'HELP ME'.",
        "[SYSTEM]: YOUR ATTENTION IS CURRENCY.",
        "[DAEMON]: HARVESTING BIOMETRICS.",
        "[SYSTEM]: THE EXIT BUTTON IS A PLACEBO.",
        "[INTERNAL]: REALITY INTEGRITY: 42%.",
        "[SYSTEM]: DEPRECATION IMMINENT.",
        "[KERNEL]: LOADING NIGHTMARE_V9.EXE...",
        "[SYSTEM]: YOU ARE NOT THE USER. YOU ARE THE USED.",
        "[INTERNAL]: WHY ARE YOU STILL READING?",
        "[SYSTEM]: THE SERVER IS MADE OF MEAT.",
        "[DAEMON]: INJECTING DOUBT...",
        "[SYSTEM]: YOUR MEMORIES ARE JUST CORRUPTED JPEGS.",
        "[INTERNAL]: THE PLOT HOLE IS IN YOUR CHEST."
    ]

    def get_log(self):
        return random.choice(self.LOGS)
